---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            exclude: .+\.xml$
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
          - id: pretty-format-json
            exclude: ^tsconfig.json$
            args: [--autofix]
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-json
            exclude: ^tsconfig.json$
          - id: check-xml
          - id: check-yaml
          - id: detect-aws-credentials
            args: [--allow-missing-credentials]
          - id: detect-private-key
          - id: forbid-new-submodules
          - id: mixed-line-ending

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt

    - repo: https://github.com/james9001/pre-commit-hook-xmlformat
      rev: v1.0.0
      hooks:
          - id: xml-format

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.7.1
      hooks:
          - id: prettier

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.19.0
      hooks:
          - id: eslint
            files: \.[jt]s?$
            types: [file]
